### ISSUE TITLE
Drupal Lessons subtasks

### ISSUE THREAD

**Issue by theodorosploumis** [theodorosploumis/notes#15]
- [ ] Organize Lessons to **Units** (small lessons) and **Bundles** (collections of Units).
- [ ] Create Bundles for each Drupal development **Role**.
- [ ] Add **estimation time** for each Unit.
- [ ] Add **achievements** for each Unit.
- [ ] Create **graphics** for each Bundle and Role.

**Comment by theodorosploumis** [comment]
Old issue: https://github.com/theodorosploumis/drupal-lessons/issues/1#issue-238883520

**Comment by theodorosploumis** [comment]
# Lessons: Theming

- Base theme and inheritance
- CSS libraries
  - which
  - external/internal
  - (core) overrides
- JS libraries
  - which
  - external/internal
  - (core) overrides
- Theme Breakpoints
- Asset bundle
  - grunt
  - bundle
  - gulp
  - phpstorm watchers
- SCSS structure
- Twig
  - folders
  - suggestions
  - embeds
  - extends
  - templates
  - variables
  - debug
- Admin theme
- Theming methodology
  - Twig templates
  - Patternlab
  - Storybook
- Styleguides
- `.theme` file
  - functions
  - hooks
  - includes
- Related modules
  - ds
  - components
  - ui_patterns
  - paragraphs
  - layout_builder
  - twig_tweak
  - twig_field_value
  - field_formatter_class
- Browser
  - which
  - extensions
  - profiles
  - local sources
- Node version (for npm packages) with `nvm`
- Git
  - `.gitignore`
  - exclude compiled (CSS/JS) files?
  - pre commit hook
- Mockups and design
  - Sketch
  - Figma
  - InvisionApp
  - XD
  - Zeplin
